# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Portal Run' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Portal Run

pod ‘Firebase/Core’
pod ‘Firebase/Database’

  target 'Portal RunTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Portal RunUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
